# NodeJS Version 16
FROM node:16.18-buster-slim

ARG CACHEBUST=1
RUN echo "Cache busting argument: $CACHEBUST"

ARG CACHE_DATE=not_a_date

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Set Env
ENV NODE_ENV production

EXPOSE 4001

# Cmd script
CMD ["npm", "run", "start"]

