version: "3.9"

services:

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
