version: "3.9"

services:

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.prod
    restart: "unless-stopped"
    environment:
      - NODE_ENV=production
