version: "3.9"

services:

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: "unless-stopped"
    command: npm install && npm run start
    environment:
      - NODE_ENV=production

