version: "3.9"

services:


  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: localhost
      DB_PORT: 27017
      DB_DATABASE: dev
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      DB_HOST: localhost
      DB_PORT: 27017
      DB_DATABASE: dev
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
